sudo: required

language: go
go:
  - "1.11"

service:
  - docker

before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.2/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - go get sigs.k8s.io/kind
  - kind create cluster

script:
  - kubectl cluster-info
