language: go
go:
  - "1.11"

service:
  - docker

matrix:
  include:
    - os: linux
      before_script:
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.2/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - go get sigs.k8s.io/kind
        - kind create cluster
        - export KUBECONFIG="$(kind get kubeconfig-path --name="1")"
    - os: windows
      before_script:
        - choco install kubernetes-cli -y
        - $TRAVIS_BUILD_DIR/kind-windows-amd64 create cluster
        - export KUBECONFIG="$(kind get kubeconfig-path --name="1")"

script:
  - kubectl cluster-info

notifications:
  email: false

